### ISSUE TITLE
Add library into Arduino repository to get easier way how to update

### ISSUE THREAD

**Issue by Eldenroot** [WifWaf/MH-Z19#19]

**Comment by WifWaf** [comment]
It should already be integrated into the Arduino Library Manager - the "library.properties" coordinates this.

It's appearing on the Arduino IDE, so should also be on PlatformIO.

Which phrase are you using for your searching?

**Comment by WifWaf** [comment]
Closing due to stagnation - let me know if you still need help (raise a new issue)
