### ISSUE TITLE
First measurement is not correct

### ISSUE THREAD

**Issue by Eldenroot** [WifWaf/MH-Z19#20]
I have mhz-19b

first measurement is not accurate, it returns always about 450 ppm, but the second if is correct (tested and compared with my second commercial device).

I use delay 60 second before the first read, is there anything what can be done better? Thank you!

**Comment by WifWaf** [comment]
Readings on bootup are erroneous, are you using the filter mode/function?

**Comment by WifWaf** [comment]
Closing due to stagnation - let me know if you still need help (raise a new issue)
