### ISSUE TITLE
Warmup always 3 minutes. Return 0x184 and 0x22B

### ISSUE THREAD

**Issue by PeterDirnhofer** [WifWaf/MH-Z19#21]
First of all: Thanks for your excellent library!
I observed during each poweroff/warmup:
myMHZ19.getCO2(false) returns 0x184 for some seconds and for the rest of the 3 minutes 0x22B.

**Comment by WifWaf** [comment]
Hey, NP  - are you getting the same values (or wrong) for 3 minutes with .getCO2(true), or just this one? 

For the first seconds, you can turn on a filter with setFilter(true), it will return 0's until it's readings are valid - see if it persists.

**Comment by WifWaf** [comment]
Closed as no further info, feel free to open if any more issues.
