### ISSUE TITLE
FYI: be warned about fake banggood MH-Z19b sensors

### ISSUE THREAD

**Issue by hixfield** [WifWaf/MH-Z19#27]
I recently ordered 3x MH-Z19 sensors from banggood. Because I wanted to construct 3 supplementary IOT CO2 sensors (refer to my project https://github.com/hixfield/HixCO2TemperatureIRBlaster). However, the readings that they produce are highly unstable and cannot be trusted. I created small YouTube video to show my readings (on request of banggood itself):

https://youtu.be/5_QQe75-SZI

Also found this post about it: https://revspace.nl/MH-Z19B#Fake_MH-Z19B_.28black_PCB.29

**Comment by WifWaf** [comment]
Cheers for the information - it's the first I've heard of this.

If it's okay with you, I'll add a note to the Readme with a link to your video.

**Comment by hixfield** [comment]
Yes sure, excellent idea!

**Comment by WifWaf** [comment]
Done. I'll leave it up for as long as they are in circulation, then move it lower down the readme.

Cheers for the info!
