### ISSUE TITLE
RAW measurement

### ISSUE THREAD

**Issue by quintendewilde** [WifWaf/MH-Z19#30]
Hi, 

I'm I correct to assume that even if my sensors range is between 410 - 2000. 

That the raw measurement that goes above 20000 is also correct? (The ppm count in the raw example)

Or is this gibberish data?

**Comment by WifWaf** [comment]
It's not gibberish exactly, however, I have no idea whether it works on other sensors and not particularly accurate.

It was based on one of my sensors at room temperature, but only up to 3500 ppm; it's mostly to indicate that exponential equations work best if it's something you want to do.

The raw value is before any calculations so, your sensor's range does not matter, however, it is affected by temperature etc.

The getCO2 command would still be the best way to get higher ppm readings.
