### ISSUE TITLE
Add MH-Z16 and below 400ppm measurements, set different range / sensititivies of sensors used.

### ISSUE THREAD

**Issue by dusjagr** [WifWaf/MH-Z19#35]
So nice to see this fantastic library. I struggled a lot 3 years ago, with all those commands... 
https://www.hackteria.org/wiki/CO2_Soil_Respiration_Chamber

From my own experiments i started to prefer the MH-Z16, as it can also send ppm values below 400. For some experiments in plant monitoring or microbiological fermentation process we can also eat up more CO2 than we release.

It's quite similar, the library could add it with minor changes.

Whaaddabout those different sensitivities 0-2000, 0-5000, 0-10'000 and even more. How can i set this up using the library?

**Comment by WifWaf** [comment]
Hey, looks like an interesting project - I like the NaOH experiment (I'm a chemist by education).

I think the main difficulty with integrating the Z16 would be testing and ensuring compatibility between all functions without inflating the code - however, I currently don't own a Z16 to carrying out any tests.

In terms of the CO2 sensitivity ranges, it can be defined with the setRange command. However, to make sure it's reasonably accurate, you also need to call zeroSpan which defines the high setpoint. I.e. if you wanted a 10,000 ppm range, you would need a reference environment of 10,000ppm - bit of a pain.

Yes, the 400ppm also a pain. The getCO2 command however shouldn't cap or floor (400ppm) the readings (at least on the Z19) . Of course, readings above the defined range are less accurate.
