### ISSUE TITLE
Library incompatible with I2C LCD?

### ISSUE THREAD

**Issue by luizedu91** [WifWaf/MH-Z19#42]
I've been using a different MHZ19 library but am having serious bugs with it so I gave yours a try, however, when I upload it the LCD doesn't work. Uploading the old sketch brings it back online. I can't understand how this would affect the screen, but I've changed nothing in my code but what's needed to make each library work.

I'm running a Leonardo, so using hardware serial, if that's relevant. 

Edit: Actually it seems like everything stopped working, the relays and the logic controlling them as well.

Any help?

**Comment by WifWaf** [comment]
It hasn't been tested on the Leonardo, however, it should work.

Any idea at which point in the sketch it's crashing? Are you able to see any prints on the serial monitor?

**Comment by WifWaf** [comment]
Okay, unfortunately without any more details I can't determine the cause.

If you use the library in future, feel free to open another issue.
